version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/application
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777
hooks:
  ApplicationStop:
    - location: server_stop.sh
      timeout: 60
      runas: ec2-user
  BeforeInstall:
    - location: server_clear.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: fix_privileges.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: server_start.sh
      timeout: 60
      runas: ec2-user