version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn clean install -DskipTests
  post_build:
    commands:
      - echo build complete

artifacts:
  files:
    - target/estoque-0.0.1-SNAPSHOT.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes